#!/bin/sh

set -ue
command_exists () {
	command -v "$@" >/dev/null 2>&1
}

DEBUGLEVEL=1

log(){
	level="$1"
	shift
	[ $DEBUGLEVEL -ge $level ] && echo "==> $@" || :
}

debug(){
	log 2 "DEBUG: $@"
}

info(){
	log 1 "INFO: $@"
}

warn(){
	log 0 "WARNING: $@"
}

error(){
	log 0 "ERROR: $@"
}
